### ISSUE TITLE
Pick data source to use during this course

### ISSUE THREAD

**Issue by tswicegood** [tswicegood/python-data-science-intro#1]
We're looking for a data source that's relatively small (500mb - 1gb), relatively clean but not perfect.  We're using this as an introduction to doing data science type work in the journalism space, so something that might be interesting to journalists is a plus.

**Comment by tswicegood** [comment]
Couple of thoughts:
- [NYC Taxi Cab](http://www.andresmh.com/nyctaxitrips/) data
- [Home Mortgage Disclosure Act](http://www.ffiec.gov/hmda/) data (see [this post](http://matthewrocklin.com/blog/work/2014/09/01/Blaze-HMDA/) for info on using it with Blaze)
- Dallas releases their crime data, but I can't find a link
- I've written a [scraper for Austin's restaurant rating](https://github.com/tswicegood/atx_restaurant_ratings) that provides some interesting data

**Comment by crccheck** [comment]
Citi Bike has a lot of raw well-structured data http://www.citibikenyc.com/system-data The good thing about this dataset is lots of other people are playing with it and doing cool things if you want an instant "wow" factor.

**Comment by tommeagher** [comment]
- [Denver Crime Data](http://data.denvergov.org/download/gis/crime/csv/crime.csv) This is about 69 mb and roughly 330k records.

**Comment by amfarrell** [comment]
http://topincomes.parisschoolofeconomics.eu/#Database:

**Comment by sarahjoannareed** [comment]
Perhaps the World Values Survey or subsets of the Uniform Crime Reports from the FBI?

**Comment by tommeagher** [comment]
Travis, with a smidge of scripting, I could piece together these [accident reports from NJ](http://www.state.nj.us/transportation/refdata/accident/master.shtm). It'd be 2001-2013 accidents, with lots of dirty town names and street names to clean. Would be more than 5 million records and about 2 gigs. 
If we wanted something smaller, we could just do 5 years of data, which would be about 1 gig.

We should decide on one soon. @richardsalex will need the data by Monday night to get them on the machines for us. What do you think, @tswicegood? We could look at the deadliest road conditions, the deadliest time of day, that kind of thing.

**Comment by tommeagher** [comment]
@tswicegood, I went ahead and put [this accident data together](https://s3.amazonaws.com/nicar15/njaccidents.csv). The file is about 760 mb and 1.7 million records. This is all the crashes in New Jersey from 2008 to 2013, from the accident table of [this NJ DoT data](http://www.state.nj.us/transportation/refdata/accident/rawdata01-03.shtm). What do you think?

**Comment by tswicegood** [comment]
That could be cool.  Good data size but not too crazy.  Let's do it.
