### ISSUE TITLE
Need a description for IRE program

### ISSUE THREAD

**Issue by tommeagher** [tswicegood/python-data-science-intro#3]
How about this for the program, @tswicegood, to send to @richardsalex?

Advanced Python for data analysis, part 1
Once you know the basics of how to scrape and ingest data in Python, you're probably itching to use it to for data analysis projects. In this hands-on workshop, we'll get you started with IPython Notebooks and pandas to do the kind of basic manipulations with code that you're used to in Excel and then walk you through the kind of analysis and manipulation you can't do in Excel. 
To get the most out of this class, you should be comfortable on the command line and the basics of the Python interpreter and its object types. 

Advanced Python for data analysis, part 2
We'll continue our dive into Python's data toolset by munging, crunching and plotting data in code. Using iPython, pandas and other libraries, we'll walk you through how they can transform, summarize, explore and visualize large data sets.
To get the most out of this class, you should be comfortable on the command line and the basics of the Python interpreter.

**Comment by tswicegood** [comment]
Looks good to me.  I'd update Part 2 to be "To get the most out of this class, you should have gone to Part 1" :-)

One question for Jaimi and company (who doesn't seem to be on GitHub): can we just put the class as one two session class instead of two separate classes?  Makes more sense to me.
